# Setup
title:               Empirical Industrial Organization
tagline:             ''
description:         'Empirical IO'
url:                 https://yingzheng-econ.github.io/Empirical-IO-Course/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ying Zheng
  url:
  email:             yingzheng@ruc.edu.cn

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-192087562-3
